name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Run SonarQube Scan
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v1

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}

  # Job 2: Build Docker Image and Scan for Vulnerabilities
  docker_build:
    name: Build Docker Image & Scan with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t your-docker-image:latest .

      - name: Install Trivy for Vulnerability Scanning
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-x86_64.deb
          sudo dpkg -i trivy_0.22.0_Linux-x86_64.deb

      - name: Run Trivy Scan
        run: |
          trivy image your-docker-image:latest

  # Job 3: Push Docker Image to Docker Hub
  docker_push:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: [docker_build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag your-docker-image:latest your-dockerhub-username/your-docker-image:latest
          docker push your-dockerhub-username/your-docker-image:latest

